[project]
name = "auth-service"
version = "0.1.0"
description = "Auth microservice"
requires-python = ">=3.12"
authors = [
    { name = "TemaDrakoshef", email = "artem125149@gmail.com" },
]
dependencies = [
    "alembic>=1.18.5",
    "bcrypt>=5.0.0",
    "grpcio>=1.83.0",
    "protobuf>=7.35.1",
    "pydantic-settings>=2.14.2",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.51",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "grpcio-tools>=1.83.0",
]
