services:
  api_gateway:
    build: .
    container_name: api_gateway
    env_file: .env
    restart: on-failure:5
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
      - auth_service
      - catalog_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
